# Generated by Django 3.2.3 on 2021-06-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0003_cliente_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rut',
        ),
    ]
