# Generated by Django 3.2.3 on 2021-07-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0006_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('Admin', 'Es el Admin'), ('Usuario', 'Eres un simple usuario'))},
        ),
    ]
